POLAR_FLS_INPUT_HEIGHT: 400 #800 # orginal img: 800 or 400
POLAR_FLS_INPUT_WIDTH: 384 # 768 # orginal img: 768 or 384

CART_FLS_INPUT_HEIGHT: 424 # orginal img: 1553 
CART_FLS_INPUT_WIDTH: 776 # orginal img: 768 or 384

pts_match_thresh: 0.6 # [-]

ransac_thresh: 0.2 # [m]

key_frames_min_dist: 1.5 # [m]
key_frames_min_rot: 0.15 # [rad]

inliers_low_threshold: 0.1
