# ========================================= #
#       Model configuration file            #
# ========================================= #

# === Encoder configuration === #
# DO NOT CHANGE 

FLS_INPUT_HEIGHT: 200 #800 # input image height
FLS_INPUT_WIDTH: 192 #768 # input image weidth

FEATURES_OUTPUT_CH: 128 # or 256; features map output channels
CONTEXT_OUTPUT_CH: 384

FEATURES_MAP_FIRST_DIM: 32 # or 64; first dimension upsize in encoder's residual block
CONTEXT_MAP_FIRST_DIM: 32

ENCODER_DOWNSIZE: 4 

ENCODER_NORM_METHOD: 'instance' # 'batch', 'group' None

# === Patchifier configuration === #

PATCHES_PER_FRAME: 10 # 48, 64, 96 - Amount of patches extracted from single frame 

PATCH_SIZE: 3 # Patch size, extracted from features map 

PATCHES_GRID_SIZE: # Size of grid that divides sonar img in equals part to extract patches evenly
  x: 30
  y: 30 

PATCHIFIER_METHOD: 'harris' # harris method with debug and visualisation functionallities

# === Graph configuration === #
INIT_FRAMES: 3 # Frames to initate graph (for traning only, in ionference INIT_FRAMES = TIME_WINDOW)

BUFF_SIZE: 10 # Ring buffer size, amount of last frames that are kept (for inference only)

TIME_WINDOW: 3 # Amount of previous frames that are taken into new edges creation

CORR_NEIGHBOUR: 5

MOTION_APPRO_MODEL: 'linear' # None

ELEVATION_INIT_MODE: 'rand' # 'zeros' or None

# === Update operation and bundle adjustment === #
UPDATE_ITERATION: 4

OPTICFLOW_WARMUP_ITER: 0

BUNDLE_ADJUSTMENT_ITERATION: 2

FREEZE_POSES: 2 



  
