# Sonar configuration
rate: 2.0 # data sampling frequency [Hz]
resolution: 
  beams: 768 # horizontal resolution - number of acustic beams
  bins: 800 # distance (vertical) resolution
fov:
  horizontal: 130 # [deg]
  vertical: 20 # [deg]
range:
  min: 0.5 # [m]
  max: 100 # [m]
position:
  x: 0.2 # [m]
  y: 0.0 # [m]
  z: 1.0 # [m]
  roll: 0.0 # [rad]
  pitch: 0.2 # [rad]
  yaw: 0.0 # [rad]


